### ISSUE TITLE
Ajuda! - Implantação framework no hostgator

### ISSUE THREAD

**Issue by flemej** [hxphp/hxphp#191]
Olá, senhores!
Depois de algum tempo afastado, estou voltando a utilizar esse framework MARA.
Estou tentando subir a minha aplicação no hostgator mas estou tendo o erro abaixo. 
Os fontes estão na pasta principal do domínio, que é public_html.
O arquio .htaccess está assim:
`Options +FollowSymLinks
Options -Indexes

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</IfModule>

<Files ~ "^\.(htaccess|htpasswd)$">
    deny from all
</Files>

<IfModule mod_deflate.c>
    <FilesMatch "\.(js|css|jpg|png|gif|ico|php|html|htm)$">
        <ifModule mod_filter.c>
            SetOutputFilter DEFLATE
            AddOutputFilterByType DEFLATE text/css text/javascript application/x-javascript text/html text/plain text/xml image/x-icon
        </IfModule>
    </FilesMatch>
</IfModule>`

E o config.php está assim:
`$configs->env->add('development');
$configs->env->development->baseURI = '/';
$configs->env->development->database->setConnectionData(array('host' => 'host', 'user' => 'user', 'password' => 'senha', 'dbname' => 'database'));
$configs->env->development->mail->setFrom(['from' => Defaults::NOME_SISTEMA, 'from_mail' => 'email@gmail.com']);
$configs->env->development->auth->setURLs('/', '/login');`

Alguém tem alguma dica?
Muito obrigado!

Fatal error: Uncaught Exception: Verifique as configuracoes de autenticacao para a subpasta: < default > in /home3/equipe11/public_html/src/HXPHP/System/Services/Auth/Auth.php:42 Stack trace: #0 [internal function]: HXPHP\System\Services\Auth\Auth->__construct(NULL, NULL, true) #1 /home3/equipe11/public_html/src/HXPHP/System/Controller.php(102): ReflectionClass->newInstanceArgs(Array) #2 /home3/equipe11/public_html/app/controllers/IndexController.php(8): HXPHP\System\Controller->load('Services\Auth', NULL, NULL, true) #3 /home3/equipe11/public_html/src/HXPHP/System/App.php(93): IndexController->__construct(Object(HXPHP\System\Configs\Config)) #4 /home3/equipe11/public_html/index.php(55): HXPHP\System\App->run() #5 {main} thrown in /home3/equipe11/public_html/src/HXPHP/System/Services/Auth/Auth.php on line 42

**Comment by skay1994** [comment]
Olá @flemej segundo o erro é falha nas configurações de autenticacao, como ta claro, porem imagino que seja por ta com o environment configurado para development, e o framework faz a detecção se ta sendo executado em localhost ou em um dominio real.

Tente passar suas configurações para o environment correto para verificar se soluciona seu problema.

```php
$configs->env->add('production');
$configs->env->production->baseURI = '/';
$configs->env->production->database->setConnectionData( array(
    'host' => 'host',
    'user' => 'user',
    'password' => 'senha',
    'dbname'   => 'database'
));
$configs->env->production->mail->setFrom([
    'from'      => Defaults::NOME_SISTEMA,
    'from_mail' => 'email@gmail.com'
]);
$configs->env->production->auth->setURLs('/', '/login');
```
